### ISSUE TITLE
Upload to npm

### ISSUE THREAD

**Issue by vuquangtam** [Noskcaj19/hyper-solarized#1]
Thank for creating this. This theme has correct colours than the others. Can you upload this to npm. I use multiple machine and it's inconvenient to download and load in localPlugins. Thanks

**Comment by Noskcaj19** [comment]
Sure, I have uploaded it to npm as `hyper-solarized-patched` and added that to the readme.

Have you tried [aravind-n/hyper-solarized](https://github.com/aravind-n/hyper-solarized)?  I believe it is based on this repo and it works for me.  It will probably get more activity than mine.
